# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Start
email: m1205123ing@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  日々気になったこととか詰まったこととか感じたこととか徒然なるままに書いていきます。
  コメント貰えると喜びます。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tashua314.github.io/" # the base hostname & protocol for your site
twitter_username: tashua314
github_username:  tashua314

# Build settings
highlighter: rouge
host: 0.0.0.0
exclude: [Rakefile, Gemfile, Gemfile.lock, README.md, vendor, node_modules]
comments :
  provider : disqus
  disqus :
    short_name : the-start
timezone: Asia/Tokyo
google_analytics: UA-79166714-1

markdown: kramdown
kramdown:
  hard_wrap: true
  coderay_line_numbers: true

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
